# Generated by Django 3.2.2 on 2021-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('video', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('quiz', models.CharField(max_length=100)),
            ],
        ),
    ]
